BigSchool/Controllers/API/CouresesController.cs
using bigschool.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace bigschool.Controllers.API
{
    public class CouresesController : ApiController
    {
		public ApplicationDbContext _dbContext { get; set; }
		public CouresesController()
		{
			_dbContext = new ApplicationDbContext();
		}

		[HttpDelete]
		public IHttpActionResult Cancel(int id)
		{
			var userId = User.Identity.GetUserId();
			var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
			if (course.IsCanceled)
				return NotFound();
			course.IsCanceled = true;
			_dbContext.SaveChanges();
			return Ok();
		}
    }
}

BigSchool/Controllers/CouresesController.cs
using bigschool.Models;
using bigschool.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bigschool.Controllers
{
    public class CouresesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public CouresesController()
        {
            _dbContext = new ApplicationDbContext();
        }
        // GET: Coureses
        [Authorize]

        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
				Heading = "Add Course"
            };
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place
            };
            _dbContext.Courses.Add(course);
            _dbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

		[Authorize]
		public ActionResult Attending()
		{
			var userId = User.Identity.GetUserId();

			var courses = _dbContext.Attendances
				.Where(a => a.AttendeeID == userId)
				.Select(a => a.Course)
				.Include(l => l.Lecturer)
				.Include(l => l.Category)
				.ToList();

			var viewModel = new CourseViewModel
			{
				UpcommingCourses = courses,
				ShowAction = User.Identity.IsAuthenticated
			};

			return View(viewModel);
		}


        [Authorize]
		public ActionResult Mine()
		{
			var userId = User.Identity.GetUserId();
			var courses = _dbContext.Courses
				.Where(c => c.LecturerId == userId && c.DateTime > DateTime.Now)
				.Include(l => l.Lecturer)
				.Include(c => c.Category)
				.ToList();

			return View(courses);
		}

		[Authorize]
		public ActionResult Edit(int id)
		{
			var userId = User.Identity.GetUserId();
			var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);

			var viewModel = new CourseViewModel
			{
				Categories = _dbContext.Categories.ToList(),
				Date = course.DateTime.ToString("MM/dd/yyyy"),
				Time = course.DateTime.ToString("HH:mm"),
				Category = course.CategoryId,
				Place = course.Place,
				Heading = "Edit Course",
				Id = course.Id
			};
			return View("Create",viewModel);
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Update(CourseViewModel viewModel)
		{
			if( !ModelState.IsValid)
			{
				viewModel.Categories = _dbContext.Categories.ToList();
				return View("Create", viewModel);
			}
			var userId = User.Identity.GetUserId();
			var course = _dbContext.Courses.Single(c => c.Id == viewModel.Id && c.LecturerId == userId);

			course.Place = viewModel.Place;
			course.DateTime = viewModel.GetDateTime();
			course.CategoryId = viewModel.Category;

			_dbContext.SaveChanges();
			return RedirectToAction("Index", "Home");
		}
	}
}

BigSchool/Views/Coureses/Mine.cshtml
@model IEnumerable<bigschool.Models.Course>
@{
	ViewBag.Title = "Mine";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mine</h2>

<ul class="course">
	@foreach (var course in Model)
	{
		<li>
			<div class="date">
				<div class="month">
					@course.DateTime.ToString("MM")
				</div>
				<div class="day">
					@course.DateTime.ToString("dd")
				</div>
			</div>
			<div class="details">
				<span class="lecturer">
					@course.Lecturer.Name
				</span>
				<span class="category">
					@course.Category.Name
				</span>
			</div>

			<div class="action">
				<a href="@Url.Action("Edit","Coureses",new { id =course.Id})">Edit</a>
				<a href="#" class="js-cancel-course" data-course-id="@course.Id">Delete</a>
			</div>
		</li>
	}
</ul>
@section scripts
{
	<script>
		$(document).ready(function () {
			$(".js-cancel-course").click(function (e) {
				e.preventDefault();
				var link = $(e.target);
				bootbox.confirm("Are you sure to delete?",
					function () {
						$.ajax({
							url: "/api/coureses/" + link.attr("data-course-id"),
							method: "DELETE"
						})
							.done(function () {
								link.parents("li").fadeOut(function () {
									$(this).remove();
								});
							})
							.fail(function () {
								alert("Something failed!");
							});
					});
			});
		});
	</script>
}